###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.3"
services:

    #PHP Service
    php-fpm:
      build: phpdocker/php-fpm
      container_name: ${APP_NAME}-php-fpm
      restart: unless-stopped
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      environment:
      - "DB_PORT=${DB_PORT}"
      - "DB_HOST=db"

    #MySQL Service
    db:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      container_name: ${APP_NAME}-mysql
      working_dir: /application
      restart: unless-stopped
      volumes:
        #- .:/application
        - ./phpdocker/db:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      ports:
        - "${DB_PORT}:${DB_PORT}"

    #Nginx Service
    webserver:
      image: nginx:alpine
      container_name: ${APP_NAME}-webserver
      restart: unless-stopped
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
       - "443:443"

    adminer:
      image: adminer
      container_name: ${APP_NAME}-adminer
      restart: unless-stopped
      ports:
        - "8080:8080"

